name: Test Builder

on:
  workflow_dispatch: {}

jobs:

  smoke:
    name: Smoke Test
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-22.04, buildjet-4vcpu-ubuntu-2204-arm ]
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Checkout
      uses: actions/checkout@v3

    # TODO: once an official `pack` release is out with multi-arch support, we probably don't need to run with the token
    - name: Run Smoke Tests
      run: ./scripts/smoke.sh -t ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
